name: lint

on:
  push:
    branches: [ collection_team ]
 # pull_request:
    # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install babel-eslint --save-dev
      - uses: sibiraj-s/action-eslint@v1
      - run: npx eslint --fix -c ~/CI/.eslintrc.json ~/source/collection_team/*.js
      
      
        #with:
          #eslintArgs: '--ignore-path=.gitignore --quiet'
          #extensions: 'js'
          #annotations: true
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #run: npm ci
          #npx eslint --fix -c ~/CI/.eslintrc.json ~/source/collection_team/*.js

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
        # run: |
          # echo Add other actions to build,
          # echo test, and deploy your project.
